services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - 5555:5555
    env_file:
      - .env
    command: gunicorn --config gunicorn.conf.py -w 4 -b ${HOST}:${PORT} flask-server:app
    volumes:
      - ./app/templates:/app/templates
      - ./app/news:/app/news
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
